### ISSUE TITLE
p2p review(29/1/2020)

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/smashing-magazine-heatmap#2]
Feel free to leave any comments or suggestions :)

**Comment by nyatindopatrick** [comment]
Excellent Work and clean code, however, I have a few remarks:

- "#guides",  ".guides" and ".design-system" exist in your css file but haven't be used anywhere in the html

**Comment by patriciachrysy** [comment]
Good job as usual, but I can see some sections of the original page missing on the heatmap. Everything that comes before the footer has been commented. Why is that?

**Comment by Kyle-Law** [comment]
Thanks for all the kind feedback! I've replied the questions above during the morning session :)
